# Generated by Django 2.0 on 2018-05-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180509_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_abstract',
        ),
    ]
